apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ems-project
  namespace: argocd

spec:
  description: EMS application project

  sourceRepos:
    - https://github.com/sunilchouhan07/GitOps-Practice.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: ems

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"


