apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-backend
  namespace: ems

spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: 015911059278.dkr.ecr.us-west-2.amazonaws.com/ems-backend:latest
          ports: 
          - containerPort: 5000

          env:
            - name: DB_NAME
              value: employee

            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            
            - name: DB_HOST
              value: ems-postgres

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 513Mi
