apiVersion: v1
kind: Service 
metadata:
  name: ems-frontend
  namespace: ems

spec:
  selector:
    app: ems-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
