apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ems
  namespace: argocd

spec:
  project: ems-project

  source:
    repoURL: https://github.com/sunilchouhan07/GitOps-Practice.git
    targetRevision: HEAD
    path: helm/ems

    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ems

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

