apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater
  namespace: argocd

spec:
  project: GitOps-Project

  source: 
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.13.0

    helm: 
      values: |
        serviceAccount:
          create: true
          name: argocd-image-updater

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

    
