apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ems

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: ems-backend

  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }} 
