apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-postgres
  namespace: ems

spec:
  replicas: {{ .Values.postgres.replicaCount }}

  selector:
    matchLabels:
      app: ems-postgres

  template:
    metadata:
      labels:
        app: ems-postgres

    spec:
      containers:
        - name: ems-postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.env.database | quote}}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 256Mi
